### ISSUE TITLE
Bug in minConvexHull ?

### ISSUE THREAD

**Issue by oqilipo** [mattools/matGeom#27]
Hi 

I've tried minConvexHull, but I get a mesh with edges with two faces on one side.
Here is the test case:
[test_minConvexHull.zip](https://github.com/mattools/matGeom/files/1212526/test_minConvexHull.zip)
One of the bad edges is marked in red here:
![minconvexhull](https://user-images.githubusercontent.com/15254908/29138482-1c06b03c-7d44-11e7-8800-cf49586a5ca0.PNG)

Thanks in advance

**Comment by dlegland** [comment]
hi,

not really a bug, but the output of minConvexHull does not impose faces to have consistent orientation. This would be interesting, however... 
I think this can easily be added, as the result is convex. I check it...

**Comment by dlegland** [comment]
Hi,

I have just made a commit that should solve the problem. You can check result of face orientation with the following:
`pfaces = minConvexHull(vertices);`  
`pFacesNormals = faceNormal(vertices, pfaces);`
`pFacesCenters = faceCentroids(vertices, pfaces);`
`figure; drawMesh(vertices, pfaces); title('min convex hull')`
`axis equal; view(3);`
`hold on ; drawVector3d(pFacesCenters, pFacesNormals)`

Hope this solves the problem?

**Comment by oqilipo** [comment]
Thank you,

I will evalute it and give feedback.

**Comment by oqilipo** [comment]
There is still an error, if you remove the last vertex of the testVertices.mat from above :
```
load('testVertices')
% Delete last vertex
vertices(end,:)=[];
% Check if all vertices are unique
assert(length(vertices)==length(unique(vertices,'rows')))
% Convex hull
faces = minConvexHull(vertices);
% Triangulate
faces = triangulateFaces(faces);
% Visualization
figure('Color','w'); view(3); axis equal tight
patch('Vertices',vertices,'Faces',faces,'FaceColor','none')
% Edges
edges = meshEdges(faces);
% Edge faces
edgeFaces = meshEdgeFaces(vertices, edges, faces);
```

```
Error using meshEdgeFaces/processFace (line 69)
Two faces were found on left side of edge 1100
```

Thanks in advance

**Comment by dlegland** [comment]
Hi,
thanks for reporting. I will investigate this ASAP...

**Comment by dlegland** [comment]
Hi,
I just had a look, and could not reproduce the bug...
Is it still up to date?

**Comment by oqilipo** [comment]
I'll check it

**Comment by oqilipo** [comment]
Seems to work. 

However, one should be aware that unreferenced vertices can remain:
```
load('testVertices')
mesh.vertices=vertices;
% Delete last vertex
mesh.vertices(end,:)=[];
% Check if all vertices are unique
assert(length(mesh.vertices)==length(unique(mesh.vertices,'rows')))
% Convex hull
mesh.faces = minConvexHull(mesh.vertices);
% Triangulate
mesh.faces = triangulateFaces(mesh.faces);
% Stats
disp(['No of components: ' num2str(numel(splitMesh(mesh)))])
trimmedMesh=trimMesh(mesh);
disp(['No of unreferenced vertices: ' num2str(size(mesh.vertices,1)-size(trimmedMesh.vertices,1))])
disp(['No of components of the trimmed mesh: ' num2str(numel(splitMesh(trimmedMesh)))])
```

```
No of components: 3
No of unreferenced vertices: 3
No of components of the trimmed mesh: 1
```

**Comment by dlegland** [comment]
Hi,
thanks for checking!
I agree, the function can be more informative about deletion of vertices. I'll check it.

**Comment by oqilipo** [comment]
Added note to the header in #205
